name: Core
version: 0.0.1-DEV
main: dev.cnbetty.core.Core
description: Core plugin for CNBetty
author: Hinterhältiger, Fledi007
website: cnbetty.dev
api-version: '1.20'
commands:
  coreidentify:
    description: outputs the current core version installed.
    usage: /coreidentify
    permission: dev.cnbetty.core.identify
  opengui:
    description: opens a basic gui for development purposes
    usage: /opengui
    permission: dev.cnbetty.core.exampleguicommand
  test:
    description: tests
  msg:
    description: privately message a player
    usage: /msg <recipient> <message>
    permission: dev.cnbetty.whisper
    aliases:
      - w
      - tell
