name: Core
version: 0.0.1-DEV
main: dev.cnbetty.core.Main
description: Core plugin for CNBetty
author: Hinterhältiger, Fledi007
website: cnbetty.dev
api-version: '1.20'
load: STARTUP
commands:
  setblockdestroystage:
    description: Test für nms
  coreidentify:
    description: outputs the current core version installed.
    usage: /coreidentify
    permission: dev.cnbetty.core.identify
  opengui:
    description: opens a basic gui for development purposes
    usage: /opengui
    permission: dev.cnbetty.core.exampleguicommand
  setblockdestroystage:
    description: test command for setting the destroy stage of the block which the player currently stands on
    usage: /setblockdestroystage <stage 0-10 >
    permission: dev.cnbetty.blockdestroystage
    aliases:
      - sbds
  msg:
    description: privately message a player
    usage: /msg <recipient> <message>
    permission: dev.cnbetty.whisper
    aliases:
      - w
      - tell
